name: Linting CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.1.4

      - name: Use Node.js 20.11
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.11
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint
